@startuml
left to right direction
actor "Неавторизованный пользователь" as nonautoriz
actor "Арендатор" as arendator
actor "Арендодатель" as arendodat

rectangle "Возможности арендатора"{
    usecase "Просмотр объявлений" as viewrent
    usecase "Отклик на объявление об аренде" as rentresponse
}
rectangle "Возможности арендодателя"{
    usecase "Создание объявления об аренде" as createrent
    usecase "Просмотр списка откликов" as viewresplist
}
usecase "Авторизация" as autoriz
nonautoriz-->autoriz
autoriz-->arendator
autoriz-->arendodat
arendodat-->viewresplist
arendodat-->createrent

arendator-->viewrent
arendator-->rentresponse

@enduml
